### ISSUE TITLE
Improve Request/Response Java API for improved developer experience 

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#108]
Anywhere there's an `Optional` result, we should consider a sibling method that helps a developer not have to throw an exception as an alternative case.

Example, in `AccountInfoResult.java`, we could add:

```
@JsonIgnore
default LedgerIndex ledgerIndexSafe() {
  return ledgerIndex().orElseThrow(IllegalArgumentException::new);
}
```

If we embrace this pattern, we should add this to every client model object.

**Comment by nkramer44** [comment]
On second thought here -- most result objects have both `ledger_index` and `ledger_current_index`, which are both optional. I think we should therefore add a method like:
```java
@Value.Auxiliary
default LedgerIndex ledgerIndexSafe() {
  return ledgerIndex().orElse(ledgerCurrentIndex()).orElseThrow(IllegalStateException::new);
}
```
