### ISSUE TITLE
OpenJDK 16 Throws Error

### ISSUE THREAD

**Issue by francisrosario** [XRPLF/xrpl4j#110]
I'm creating a XRP Wallet Tool but it seems the xrpl4j lib doesn't work on OpenJDK 16, I've tried using Amazon Cornetto 11 it works fine without any problem.

Need some advice regarding this problem

![image](https://user-images.githubusercontent.com/8011433/119720750-f173b600-be9c-11eb-8601-899d1e40f4d7.png)

**Comment by sappenin** [comment]
This is very interesting, thanks for reporting it! 

It appears to be a problem with Feign client, from what I can tell. I don't think [we're building xrpl4j in CI](https://github.com/XRPLF/xrpl4j/blob/main/.github/workflows/workflow.yml#L55) on Java 16 yet, so I think the next step is to try that out and see if tests pass in a dev build.

**Comment by francisrosario** [comment]
https://xrptools.herokuapp.com/

Thanks, I'm building for the XRP Grant; Since Java 16 isn't yet supported I've changed my method of servlet implementation on a lower version of java.. Looking forward to Java 16 compatibility! :)

**Comment by nkramer44** [comment]
Hey @francisrosario, thanks for bringing this up! 

This is a known issue with Open Feign in JDK16 (see here: https://github.com/OpenFeign/feign/issues/935) and has to do with how reflective access is handled in JDK16.

I was able to reproduce the error locally, and was able to fix it by adding these arguments:
`--illegal-access=warn --add-opens java.base/java.lang.invoke=ALL-UNNAMED`

Unfortunately, this is a bit of a workaround, and the `--illegal-access` argument may be removed in Java versions > 16, but for now it should work.

**Comment by francisrosario** [comment]
Alright thanks for the feedback regarding this matter.
