### ISSUE TITLE
Unable to instantiate XrplClient object

### ISSUE THREAD

**Issue by xrpdevs** [XRPLF/xrpl4j#113]
I'm just getting started with XRPL4J (libs imported into Android Studio), and have an issue:

```
HttpUrl rippledUrl = HttpUrl.get("https://s.altnet.rippletest.net:51234/");

XrplClient xrplClient = new XrplClient(rippledUrl);
```

I get an error:
`java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field IMPL_LOOKUP in class Ljava/lang/invoke/MethodHandles$Lookup; (declaration of 'java.lang.invoke.MethodHandles$Lookup' appears in /apex/com.android.runtime/javalib/core-oj.jar)`

Any pointers would be useful - I'm using v2.0.0 of the libraries.

**Comment by xrpdevs** [comment]
The issue wasn't with XRPL4J but with OpenFeign/feign-core

Forked and fixed for Android compatibility at https://github.com/xrpdevs/feign

PR submitted to OpenFeign

HTH some Android developers out there.

**Comment by soaryong** [comment]
@xrpdevs how can solve?
