### ISSUE TITLE
The privateKey field in the Wallet.builder() method is out of date?

### ISSUE THREAD

**Issue by Smilestate** [XRPLF/xrpl4j#115]
I was thinking, I built a wallet class when I transferred money, but adding a privateKey shows that the field is out of date. Will it affect the wallet object I constructed?
And, I also want to ask that the seed can generate private and public keys, so is there a way to infer the seed based on the private and public keys?
Looking forward to your reply

**Comment by sappenin** [comment]
> I built a wallet class when I transferred money, but adding a privateKey shows that the field is out of date.

I'm not sure I follow - can you clarify?

> ...so is there a way to infer the seed based on the private and public keys?

No, private-key generation from a seed is a one-way function. You can read more [here](https://xrpl.org/cryptographic-keys.html#key-derivation).

**Comment by Smilestate** [comment]
But I have a question. I used the mnemonic phrase to generate the address, private key, public key, and seed in BIP39. However, I found that the generated seed is obviously different from the seed specified by ripple. May I ask if there is a special encoding format. It is best to provide a code reference!

**Comment by nkramer44** [comment]
Yes, XRPL seeds are encoded a bit differently than BTC seeds. Both are Base58 encoded with a checksum, but XRPL seeds and addresses use a different alphabet than BTC seeds/addresses. More information [here](https://github.com/XRPLF/xrpl4j/blob/b04ddf4265f865dcdd80093ef1599c258f7e8d16/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountSetIT.java#L44)

**Comment by Smilestate** [comment]
> 是的，XRPL种子的编码方式与BTC种子略有不同。两者都是用校验和编码的Base58，但XRPL种子和地址使用与BTC种子/地址不同的字母表。更多信息[在这里](https://github.com/XRPLF/xrpl4j/blob/b04ddf4265f865dcdd80093ef1599c258f7e8d16/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountSetIT.java#L44)

It seems that the link address is wrong here, it looks like the account is set up.
