### ISSUE TITLE
How to set the account requires destinationTag?

### ISSUE THREAD

**Issue by Smilestate** [XRPLF/xrpl4j#116]
I used your address in the test class, checked it in the block explorer, and found that your account needs a destination tag. Then I would like to ask how to set the required destination tag for my registered account?

**Comment by francisrosario** [comment]
Using the Payment.builder() you can add .destinationTag(UnsignedInteger.valueOf(transactiontag))

**Comment by Smilestate** [comment]
I am not referring to sending xrp transactions!  
I mean that lsfDefaultRipple can be seen on a certain account on the block explorer
lsfDisableMaster
lsfRequireDestTag these special fields

**Comment by nkramer44** [comment]
@Smilestate Are you asking how to set the `lsfRequireDestTag` on your account? 

If so, you can submit an `AccountSet` transaction with the `setFlag` field set to `AccountSetFlag.REQUIRE_DEST`.
Take a look at [`AccountSetIT`](https://github.com/XRPLF/xrpl4j/blob/b04ddf4265f865dcdd80093ef1599c258f7e8d16/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountSetIT.java#L44) for an example of how to do this.

**Comment by Smilestate** [comment]
> @Smilestate你问如何`lsfRequireDestTag`在你的帐户上设置？
> 
> 如果是这样，您可以提交一个字段设置为的`AccountSet`交易。 看一下如何执行此操作的示例。`setFlag``AccountSetFlag.REQUIRE_DEST`
> [`AccountSetIT`](https://github.com/XRPLF/xrpl4j/blob/b04ddf4265f865dcdd80093ef1599c258f7e8d16/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountSetIT.java#L44)

Thank you very much, the problem is solved. But I did not see this method in the official documentation!
