### ISSUE TITLE
Failed to parse a transaction in the ledger?

### ISSUE THREAD

**Issue by Smilestate** [XRPLF/xrpl4j#117]
When I use xrplclient.transaction to parse the transaction, and under the payment condition, I found that the amount field is inconsistent, and there are xrp transfers and other currency transfers in the ledger. What makes me headache is that the amount is XrpCurrencyAmount when parsing the xrp transfer. When analyzing other currencies, it is ImmutableIssuedCurrencyAmount. What I want to ask is how to distinguish between xrp payment and other.
The transaction hash in question is 5E089C0CD4C52D3ECD85E5E1F38FC255F43FAFAF4FD5C42DD48A8A1B6C36DF5E.
The correct xrp payment transaction is 2AB2C29C22F7ADDA7F9FB1230646C48485A535442BD97BDEF748C00D0B3A8F43.
Finally, if it is convenient, can you pull me into the community exchange group or WeChat group?

**Comment by nkramer44** [comment]
Did you see an error when calling `xrplClient.transaction` or are you just asking how to distinguish between the different types in the `Payment.amount` field?

If I'm understanding correctly, you are just asking how to figure out if a `Payment` was an XRP payment or an issued currency payment. Is that correct? If so, if a `Payment` is an XRP payment, the `amount` field will be of type `XrpCurrencyAmount`, which is just a wrapper of `UnsignedLong`. If the `Payment` was an issued currency payment, the `amount` field will be of type `IssuedCurrencyAmount`, which has three fields (see [here](https://xrpl.org/currency-formats.html#currency-formats)).

Both `XrpCurrencyAmount` and `IssuedCurrencyAmount` extend `CurrencyAmount`, which has two convenient methods to handle either case. See [`CurrencyAmount`](https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/CurrencyAmount.java)

**Comment by Smilestate** [comment]
> 您是在调用时看到错误`xrplClient.transaction`还是只是询问如何区分`Payment.amount`字段中的不同类型？
> 
> 如果我理解正确，您只是在问如何确定 a`Payment`是 XRP 付款还是已发行的货币付款。那是对的吗？如果是这样，如果 a`Payment`是 XRP 付款，则该`amount`字段的类型为`XrpCurrencyAmount`，它只是`UnsignedLong`. 如果`Payment`是已发行的货币付款，则该`amount`字段的类型为`IssuedCurrencyAmount`，其中包含三个字段（请参阅[此处](https://xrpl.org/currency-formats.html#currency-formats)）。
> 
> 既`XrpCurrencyAmount`和`IssuedCurrencyAmount`延伸`CurrencyAmount`，它有两个方便的方法来处理这两种情况下。看[`CurrencyAmount`](https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/CurrencyAmount.java)

When I looked at the source code, I saw the distinction. I was similar to this before. I was the object to get the result, and then to judge whether it was XrpCurrencyAmount, or just filter it out. This is the same as the xrplclient processing method, but I think your method is more attractive and professional, I still use isAssignableFrom to distinguish, it feels more convenient and the code is more readable.
Finally, thank you very much for your reply.
