### ISSUE TITLE
xrplClient will the request be restricted?

### ISSUE THREAD

**Issue by Smilestate** [XRPLF/xrpl4j#118]
I have used xrplclient in the project, but I have always had a question, that is, will the use of xrplClient request be restricted? If restricted, how many requests are allowed per second?

**Comment by nkramer44** [comment]
The `XrplClient` will never have rate limited access on the client side. However, all of the available public rippled nodes limit the number of requests from any given IP address. I don't know off the top of my head what this limit is, but I personally have never run into it.  See [Rate Limiting](https://xrpl.org/rate-limiting.html#rate-limiting) for more info

**Comment by nkramer44** [comment]
Also, the current underlying network client used in `XrplClient` will automatically retry requests after rippled responds with a 503 status (Service Unavailable).
