### ISSUE TITLE
Re: Domain value

### ISSUE THREAD

**Issue by francisrosario** [XRPLF/xrpl4j#119]
Having like that in the Transaction.java would be helpful... It gets the domain value from a specific transaction.

```
   /**
   * The domain that owns this account, as a string of hex representing the ASCII for the domain in lowercase
   *
   *
   * @return An {@link Optional} {@link String} containing the domain value.
   */
  @JsonProperty("domain")
  Optional<String> domain();
```

**Comment by nkramer44** [comment]
Unfortunately that `domain` field is a part of the `AccountRoot` object, so without making another call to rippled for every transaction to get the source account, this isn't really possible. However, you can take the `account` field from any given `Transaction` and make an `XrplClient.accountInfo` call with that address to get the `domain` you're looking for. 

Do you have any idea how common it is for accounts to have domains associated with them? I've personally never seen one, but also haven't looked too hard.

**Comment by francisrosario** [comment]
> Unfortunately that `domain` field is a part of the `AccountRoot` object, so without making another call to rippled for every transaction to get the source account, this isn't really possible. However, you can take the `account` field from any given `Transaction` and make an `XrplClient.accountInfo` call with that address to get the `domain` you're looking for.
> 
> Do you have any idea how common it is for accounts to have domains associated with them? I've personally never seen one, but also haven't looked too hard.

Thanks for that information :D @nkramer44 , it Works fine now .. Highly appreciate your quick response. 
![image](https://user-images.githubusercontent.com/8011433/123699706-286d2b00-d892-11eb-9683-11124968b870.png)
