### ISSUE TITLE
Transfer problem?

### ISSUE THREAD

**Issue by Smilestate** [XRPLF/xrpl4j#131]
Today, I did a very interesting experiment on transfers.
First of all, I prepared the transfer method, which is implemented through xrplClient.submit. I looped this method 20 times and performed 20 transfers, and then I was surprised to find that the same hash actually exists, and one thing in common under the same hash is that the ledger index is the same. Is there a problem with the code or the mechanism of ripple?

**Comment by Smilestate** [comment]
Add as follows：
Running the SendXrp sample...3
19650489
Optional[D38A18E370FB28BD0BB3DC6F2FA14354DA8B2271129B90F9F3A944146BA8FAB0]
Running the SendXrp sample...4
19650489
Optional[D38A18E370FB28BD0BB3DC6F2FA14354DA8B2271129B90F9F3A944146BA8FAB0]

The above execution result is executed in a loop, and this exception is found in the third and fourth executions. The hash generated is consistent.

**Comment by nkramer44** [comment]
Can you please provide the code from your example? It's difficult to figure out what might be happening without seeing code. Thanks!

**Comment by Smilestate** [comment]
for (int i = 1; i < 20; i++) {
            System.out.println("Running the SendXrp sample..." + i);

            // 创建客户端
            final HttpUrl rippledUrl = HttpUrl.get("https://s.altnet.rippletest.net:51234/");
            XrplClient xrplClient = new XrplClient(rippledUrl);

            KeyPairService service = DefaultKeyPairService.getInstance();
            Address address = service.deriveAddress("KEY");

            WalletFactory walletFactory = DefaultWalletFactory.getInstance();

            // 构建钱包对象
            final Wallet testWallet = Wallet.builder()
                    .publicKey(XrpUtil.upKey("publicKey"))
                    .privateKey(XrpUtil.upKey("privateKey"))
                    .isTest(false)
                    .xAddress(XAddress.of(""))
                    .classicAddress(address).build();

            // 获取钱包地址
            final Address classicAddress = testWallet.classicAddress();

            // 查看账号验证后的sequence
            final AccountInfoRequestParams requestParams = AccountInfoRequestParams
                    .builder().ledgerIndex(LedgerIndex.VALIDATED)
                    .account(classicAddress)
                    .build();

            final AccountInfoResult accountInfoResult = xrplClient.accountInfo(requestParams);
            final UnsignedInteger sequence = accountInfoResult.accountData().sequence();

            // 从rippled请求当前费用信息
            final FeeResult feeResult = xrplClient.fee();
            final XrpCurrencyAmount openLedgerFee = feeResult.drops().openLedgerFee();

            UnsignedInteger lastLedgerSequence = UnsignedInteger.valueOf(xrpLedgerResult.getLedgerIndex() + 4L);

            // 构建付款对象
            ImmutablePayment.Builder build = Payment.builder()
                    .account(classicAddress)
                    .amount(XrpCurrencyAmount.ofXrp(new BigDecimal(12)))
                    .destination(Address.of("address"))
                    .sequence(sequence)
                    .fee(XrpCurrencyAmount.ofXrp(new BigDecimal("0.000012")))
                    .signingPublicKey(testWallet.publicKey())
                    .lastLedgerSequence(lastLedgerSequence);
            Payment payment = build.build();

            // 构造一个 SignatureService来签署支付
            PrivateKey privateKey = PrivateKey.fromBase16EncodedPrivateKey(testWallet.privateKey().get());
            SignatureService signatureService = new SingleKeySignatureService(privateKey);

            // 签署付款
            final SignedTransaction<Payment> signedPayment = signatureService.sign(KeyMetadata.EMPTY, payment);

            // 提交付款
            final SubmitResult<Transaction> submitResult = xrplClient.submit(signedPayment);
            System.out.println(submitResult.transactionResult().transaction().hash());
        }

**Comment by Smilestate** [comment]
In theory, there is no reason to repeat the sequence!

**Comment by nkramer44** [comment]
```java
final AccountInfoRequestParams requestParams = AccountInfoRequestParams
          .builder().ledgerIndex(LedgerIndex.VALIDATED)
          .account(classicAddress)
          .build();
```

Here is your problem. By sending an `account_info` request with `ledgerIndex = "validated"`, you are asking rippled for your account info _as of the most recently validated ledger_.  Since you are submitting multiple transactions in a row very quickly, most of them will get submitted to the same working ledger (ledgers get validated every 3-5 seconds). Each transaction will use the next account sequence number, but your current account sequence number will not be reflected yet in the most recently validated ledger.

Instead, try getting your `"current"` account info like this:
```java
final AccountInfoRequestParams requestParams = AccountInfoRequestParams.builder()
          .ledgerIndex(LedgerIndex.CURRENT)
          .account(classicAddress)
          .build();
```

**Comment by francisrosario** [comment]
> ```java
> final AccountInfoRequestParams requestParams = AccountInfoRequestParams
>           .builder().ledgerIndex(LedgerIndex.VALIDATED)
>           .account(classicAddress)
>           .build();
> ```
> 
> Here is your problem. By sending an `account_info` request with `ledgerIndex = "validated"`, you are asking rippled for your account info _as of the most recently validated ledger_. Since you are submitting multiple transactions in a row very quickly, most of them will get submitted to the same working ledger (ledgers get validated every 3-5 seconds). Each transaction will use the next account sequence number, but your current account sequence number will not be reflected yet in the most recently validated ledger.
> 
> Instead, try getting your `"current"` account info like this:
> 
> ```java
> final AccountInfoRequestParams requestParams = AccountInfoRequestParams.builder()
>           .ledgerIndex(LedgerIndex.CURRENT)
>           .account(classicAddress)
>           .build();
> ```

I agree with this, He sends his transaction way too fast...
He also can do something similar to this one.
```java
do {
                        
                    }
                }
                initialMarker++;
                boolean isValidated = false;
                do{
                    if(lg.getledgerResult(initialMarker).validated()){
                        isValidated = true;
                    }
                    TimeUtils.sleepFor(800, TimeUnit.MILLISECONDS);
                }while(!isValidated);
            }while(loop);
```
