### ISSUE TITLE
Hash computation in SignedTransaction doesn't compute correctly for Mutlisig transactions

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#152]
The prefix for a Single vs Multi Signed transaction is different.

**Comment by sappenin** [comment]
Per our discussion, in the encoder, we'll likely need to reorder the signers in JSON before we transmute the JSON to binary in order to make the hash computation correctly in the case of multisig.

**Comment by mukulljangid** [comment]
Addressed here : https://github.com/XRPLF/xrpl4j/pull/257
