### ISSUE TITLE
Correct IllegalArgumentException message in `TransactionType`

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl4j#159]
If you try to construct a `TransactionType` that doesn't exist using `TransactionType.forValue(String)`, the method throws an `IllegalArgumentException`. 

This exception is correct, but the message that we attach to it is incorrect (due to copy pasting poorly). Currently, the exception is:
```
throw new IllegalArgumentException("No matching AccountSetFlag enum value for int value " + value);
```

We should fix the message by changing it to 
```
throw new IllegalArgumentException("No matching TransactionType enum value for String value " + value);
```

**Comment by awydini** [comment]
May I work on this issue?

**Comment by sappenin** [comment]
Yes, plz do!
