### ISSUE TITLE
Refactor project modules to improve developer experience

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#185]
In order to use xrpl4j `v1.x` and `v2.x`, a developer must import a variety of maven coordinates in their `pom.xml` project files.

Instead, it would be preferable to have (nearly) all library code in a single module called `xrpl4j-core` so that a developer only has to import a single dependency to utilize the entire library.

Once complete, the following will be the only two modules in the project:

* `xrpl4j-core` (e.g., a service that creates signatures but doesn't need a client)
* `xrpl4j-intergration-tests` (not in bom)

Maybe...
* `xrpl4j-crypto` (parent module (to allow for both BC and Java17 implementations)
* `xrpl4j-bom` (needed if there's more than 1 module that devs would use).
* `xrpl4j-client` (e.g., do we want to force anyone pulling in `core` to also take a WS and RPC client)

**Comment by mukulljangid** [comment]
I like the first one with only 2 modules. Example, for `xrpl4j-client`, what are the chances that a user of the library will not need a client.

**Comment by sappenin** [comment]
We probably want to make it easy to depend on the JSON-RPC client without a WS client, and vice-versa.

**Comment by nkramer44** [comment]
Final plan:

* xrpl4j-core
* xrpl4j-client
* xrpl4j-integration-tests
* xrpl4j-bom
* xrpl4j-parent
