### ISSUE TITLE
Fix Javadoc errors on JDK > 11

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#202]
On more modern JDKs (e.g., Java17) the build breaks due to insufficient Javadoc coverage.

However, in the build we disable Javadoc creation (see [here](https://github.com/XRPLF/xrpl4j/blob/main/.github/workflows/workflow.yml#L95)) but we should probably add proper Javadoc comments and then re-enable the doc gen (at least on Java17 only maybe).

**Comment by mukulljangid** [comment]
I took some time to look into this. The only errors I ended up seeing were from the generated-sources. Basically, the exclusion [here](https://github.com/XRPLF/xrpl4j/blob/759f56bdda3fb39022a4b3536c1d6b0a7d7f9f2b/pom.xml#L417) isn't working. And I couldn't get it to work.

**Comment by sappenin** [comment]
OK, I think we can close this one now. That said, when working on code, it would be good to cleanup javadoc errors on files that you touch (assuming they're not generated files that is).
