### ISSUE TITLE
Unsupported Currency representation: GALAXY

### ISSUE THREAD

**Issue by tinshen** [XRPLF/xrpl4j#217]
Address r3Si5cWtHZZuKXQERoaTKc7Vhw53RdGi2A
name Galaxy
=====================
IssuedCurrencyAmount can't support name's Galaxy
ISO_REGEX = Pattern.compile("^[A-Z0-9]{3}$");

**Comment by tinshen** [comment]
https://xrpl.org/currency-formats.html#nonstandard-currency-codes

**Comment by nkramer44** [comment]
Hi @tinshen, I am assuming that you were able to solve this since you closed the issue, but want to make sure you aren't still having trouble.

**Comment by tinshen** [comment]
> Hi @tinshen, I am assuming that you were able to solve this since you closed the issue, but want to make sure you aren't still having trouble.

tks.
I have solved the problem.
