### ISSUE TITLE
CurrencyType ISO_REGEX should allow lower case

### ISSUE THREAD

**Issue by barryrknapp** [XRPLF/xrpl4j#220]
org.xrpl.xrpl4j.codec.binary.types.CurrencyType ISO_REGEX should be
Pattern ISO_REGEX = Pattern.compile("^[a-zA-Z0-9]{3}$");

See the following raw transaction using xSD 
https://xrpscan.com/tx/E85D3875DF1A8674A9A5D5FAE503314BEEF80F2C9E2151F5C05E7A22E77CA023

vs this raw transaction which tried to use the hex for xSD instead 
https://xrpscan.com/tx/5C9D8C8D1E954F05CA8F8BBA158BB39DF695E5FD0941FD829F08A4F4FBAB1760

**Comment by sappenin** [comment]
Thanks for opening this issue @barryrknapp -- see PR here (https://github.com/XRPLF/xrpl4j/pull/222).

**Comment by sappenin** [comment]
This is now fixed and slated for v2.2.1. If you want depend on it beforehand, you can try [jitpack here](https://jitpack.io/#xrplf/xrpl4j/9f7d74e537).
