### ISSUE TITLE
Cannot deserialize value of type `java.time.ZonedDateTime`

### ISSUE THREAD

**Issue by zhoushuntong** [XRPLF/xrpl4j#243]
// Get the latest validated ledger index
    LedgerIndex validatedLedger = xrplClient.ledger(
            LedgerRequestParams.builder()
                    .ledgerIndex(LedgerIndex.VALIDATED)
                    .build()
    )
            .ledgerIndex()
            .orElseThrow(() -> new RuntimeException("LedgerIndex not available."));

**Comment by Smilestate** [comment]
> // Get the latest validated ledger index LedgerIndex validatedLedger = xrplClient.ledger( LedgerRequestParams.builder() .ledgerIndex(LedgerIndex.VALIDATED) .build() ) .ledgerIndex() .orElseThrow(() -> new RuntimeException("LedgerIndex not available."));
I think if you upgrade the sdk version to 2.2.0 or higher, the error will not be prompted! I also had this problem when I used 2.0.0 to traverse old blocks. Change to version 2.2.0 will not have this problem!

**Comment by nkramer44** [comment]
Hi @zhoushuntong, as @Smilestate said, version 2.2.0 of xrpl4j fixes this issue. Please feel free to re-open if you still have problems after upgrading.
