### ISSUE TITLE
Enable CodeCoverage monitoring as part of the build

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#26]
We should enable CodeCoverage monitoring as part of the build. See https://codecov.io/gh/hyperledger/quilt for e.g., or some other tool.

**Comment by alloyxrp** [comment]
I have enabled codecov - @nkramer44 please confirm if this is working as expected?

**Comment by nkramer44** [comment]
@alloyxrp Yes working as expected.  Just need to get my config right!
