### ISSUE TITLE
Transaction List from ledger Index

### ISSUE THREAD

**Issue by sera-korbit** [XRPLF/xrpl4j#289]
hello, XRP Team.
I was trying to get all transactions from a specific ledger index using xrplClient.
Specifically, I would like to get a list of specific token transactions (like SOLO token) on a specific ledger index.
But I haven't been able to find a proper way to solve this.
XRPLclient has 'transaction methods' that can only get transaction information from Transaction Hash.
Is there any way to solve this problem?

**Comment by sappenin** [comment]
Hi @sera-korbit -- I think the `accountTransactions` method in XrpClient is what you're looking for. Note that you'll want to filter the transactions that come back to look for only payments that involve `SOLO` or whatever you're looking for.

**Comment by sappenin** [comment]
Please re-open this issue if you have further issues. Also, for future general tech-support type questions, please consider opening a Discussion instead of an issue. Thanks!
