### ISSUE TITLE
Can not sync block with transaction on some block with NFT tx

### ISSUE THREAD

**Issue by wandapen** [XRPLF/xrpl4j#321]
when sync block info on some block  contains NFT tx, will trigger JsonMappingException with msg "TransferFee should be in the range 0 to 9999" , in raw string result, the TransferFee is 10000; 
example block:
75602124
my code: (blockNumber = 75602124)
                UnsignedInteger index = UnsignedInteger.valueOf(blockNumber);
                LedgerResult ledgerResult = xrplClient.ledger(LedgerRequestParams.builder()
                        .ledgerSpecifier(LedgerSpecifier.of(LedgerIndex.of(index))).transactions(true)
                        .build());

**Comment by wandapen** [comment]
xrpl4j version 2.5.0

**Comment by mukulljangid** [comment]
The issue has been fixed.
