### ISSUE TITLE
Add pre-release support for Hooks Transactions

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#39]
@nhartner can you publish your branch that has Hooks transaction support?

**Comment by nhartner** [comment]
Hooks stuff is on a branch: https://github.com/XRPLF/xrpl4j/tree/hooks-dev-preview.  HooksIT shows an example. I don't think we should merge this branch into master because Hooks API is not close finalized and it's only possible to run this using a forked version of rippled.

**Comment by sappenin** [comment]
Agreed. Closing this issue for now since we're not going to work on it in the short-term, and this issue will be here for posterity (as will the dev branch linked above).
