### ISSUE TITLE
ShaMap ?? 

### ISSUE THREAD

**Issue by sublimator** [XRPLF/xrpl4j#418]

**Comment by sappenin** [comment]
Let's start a discussion around this. Mind posting something over in https://github.com/XRPLF/xrpl4j/discussions ?

**Comment by sublimator** [comment]
I was just surprised there was none there! 
I guess there's no use for it (yet) ?

**Comment by nkramer44** [comment]
The ShaMap is the data structure that the XRPL stores its data in. The data is exposed to clients via an API (RPC, WS), but is only useful if you're storing the entire ledger and want to be a validator on the network. xrpl4j is simply a client library that supports interacting with the XRPL and doesn't aim to be a tool that could be used to build an XRPL node, so I don't think we will ever add a ShaMap to this library. 

I'm going to close this issue, but feel free to open it up again or start a Discussion if you feel having a ShaMap in this library would be useful.
