### ISSUE TITLE
LedgerResult Deserialization: Negative Balance in AccountRoot AffectedNode

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl4j#474]
Some historical transactions have metadata for a change in an `AccountRoot` object where the `Balance` of the account is negative. `AccountRootObject` and `MetaAccountRootObject` `balance` is typed as an `XrpCurrencyAmount` which doesn't allow for negative numbers. We should figure out how this is possible because negative balances shouldn't be allowed.

Ledgers where this is a problem:
* ED4395F2C503963E0E9A37F36F5ACC8A60DD9911A1F9E61F71AF555003C1F53B
* 3FA4E5A1B2DA2F27FD2E3DD3AB7487441F65F4349126F4AFC9F67FD07ECB7D3D
* D840709E9075A5DC5D2C6D7E45728B76102B3A5CD22BCF4793C47959A3ECEC2A
* 3E6571E1869FD143E6558251007F511CDF008EBA62F585E2B3FFD51191ED4B44
* 892B13707B9031258D57ED9F42BAAC2BD63EC553E177F5DE0F63BD1EE124F24A
* BD93D52FDDE2E57825FC038B6CE8B19F22388FC2D96161AB75844A5D793113AE
* 4D08EE303097D13775C22674672527055625E8115635C0A0FF8BA714F9474286
* 024BA9BD6BF8C5289C19F742514168701523975B261198EDC6707B9032B051D1

**Comment by sappenin** [comment]
This has been fixed via https://github.com/XRPLF/xrpl4j/pull/535. Please upgrade to [v3.5.0](https://github.com/XRPLF/xrpl4j/releases/tag/v3.5.0) or above.
