### ISSUE TITLE
LedgerResult Deserialization: AccountSet SetFlag/ClearFlag can be any 32 bit number

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl4j#477]
The docs say that the `AccountSet` `SetFlag` and `ClearFlag` must be a number between 1 and 15 (ie must be no more than 4 lowest bits set). However, there are some historical `AccountSet` transactions that has `SetFlag` or `ClearFlag` set to 4294967295, which is that max unsigned 32 bit number. This transaction does nothing because the `AccountSet` transactor checks for equality between `SetFlag`/`ClearFlag` and certain `asf` flags, but it does break our deserialization. This is because `AccountSetFlag` is an enum that wraps an `int`, and 4294967295 is too large for Java signed ints. 

The `@JsonCreator` on `AccountSetFlag` is public, so we can't just make it take a `long` instead of an `int` without a breaking change. However, we should probably add another method that takes a `long` and returns a new enum value called `UNKNOWN` or `NONE` if the flag is unrecognized rather than throwing an exception.

We should also consider filing a bug in rippled, as the transactor should likely limit the `SetFlag` and `ClearFlag` to the established `asf` flag values and return an error code if not.

Ledgers where this is a problem:
* 596C086FA83918033DF1A7FF31CA1D3E3526DE0533217A8A324D97DF7CA39E98

**Comment by SomerGG** [comment]
I also encountered this error, please fix it as soon as possible @sappenin 
version: 3.1.2
network: testnet
block Number: 40232147
