### ISSUE TITLE
Make it easier to get the amount of an XRP payment as BigDecimal

### ISSUE THREAD

**Issue by nhartner** [XRPLF/xrpl4j#49]
The way amounts are mapped could be more convenient to use. In most cases, people just want to get the amount in XRP as a decimal, not drops. But on things like payments, that requires doing an` instanceof` then a cast to `XrpCurrencyAmount` then no obvious way to get the decimal value (instead of drops) from there

**Comment by sappenin** [comment]
Any opinions around how you'd like to see this implemented? My initial solution is something like this (but jury is still out about its level of convenience):

# Payment.java
```
@Derived
@Lazy
default Optional<XrpCurrencyAmount> amountAsXrp() {
  if (XrpCurrencyAmount.class.isAssignableFrom(amount().getClass())) {
    return Optional.of((XrpCurrencyAmount) amount());
  } else {
    return Optional.empty();
  }
}
```

# _XrpCurrencyAmount
```java
static BigDecimal toXrp(XrpCurrencyAmount xrpCurrencyAmount) {
  return new BigDecimal(xrpCurrencyAmount.value().bigIntegerValue())
    .divide(BigDecimal.valueOf(1000000), MathContext.DECIMAL128);
}
```

Usage would be something like this:

```java
Payment payment = ...
BigDecimal amountOfXrp = payment.amountAsXrp()
  .map(XrpCurrencyAmount::toXrp)
  .orElse(BigDecimal.Zero); // <-- allows the caller to decide whether to supply a default or throw.
```

Note that It's unclear what the result of calling `Payment.amountAsXrp()` should be if the `amount` isn't XRP (e.g., if it's an `IssuedCurrencyAmount`), so I chose to use `Optional` for easier mapping of a default value by the consumer of this solution. But throwing an exception in `amountAsXrp()` is an alternative I suppose.

**Comment by sappenin** [comment]
Checkout https://github.com/XRPLF/xrpl4j/pull/68 for how this could look in practice.
