### ISSUE TITLE
LedgerResult Deserialization: Invalid but parseable EscrowFinish fulfillment

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl4j#513]
Certain fulfillments and conditions that show up in validated (but not executed) EscrowFinish transactions are able to be parsed by `CryptoConditionReader`, but are actually malformed (for example if a Fulfillment has a well formed first 32 bytes, but has extra bytes attached afterward). This causes an exception to be thrown when deserializing the EscrowFinish from JSON. 

Offending transactions:
- https://livenet.xrpl.org/transactions/138543329687544CDAFCD3AB0DCBFE9C4F8E710397747BA7155F19426F493C8D

**Comment by sappenin** [comment]
What should the fix logic be here?
