### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported Currency representation of (Coin Format for ISO)[a-zA-Z]{3}

### ISSUE THREAD

**Issue by Try-Parser** [XRPLF/xrpl4j#519]
Hi guys i just have questions if this library only support 3 character coin in CurrencyType as i saw in the 

https://github.com/XRPLF/xrpl4j/blob/3c4a07692e8debf1aacb7ef924a47d8c8b2e07fa/xrpl4j-core/src/main/java/org/xrpl/xrpl4j/codec/binary/types/CurrencyType.java#L65-L72

example : 
```
    "taker_get": {
        "value": "10",
        "currency": "XRP"
    },
    "taker_pay": {
        "value": "1000000",
        "currency": "SHIB",  > 3 = Unsupported currency representation
        "issuer": "raGYAQYuvZXxQmE53TA5cRcCBM2DRuhkJk"
    }
```

**Comment by sappenin** [comment]
Hi @Try-Parser - thanks for your question. 

The library _does_ support issued currency codes that are longer than 3 characters. However, you'll need to hex-encode them. Only `XRP` and 3-character ISO codes are supported in raw text.

For an example of how this can work in Java, see [here](https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/IssuedCurrencyIT.java#L80).

And for a full description, you can read more here about how [currency codes work](https://xrpl.org/currency-formats.html#standard-currency-codes).

**Comment by Try-Parser** [comment]
Hi @sappenin that make sense thank you for responding ill close this ticket
