### ISSUE TITLE
SetHook Transaction type

### ISSUE THREAD

**Issue by etherum123** [XRPLF/xrpl4j#532]
Is there any intention on adding the SetHook transaction type to the code?

**Comment by sappenin** [comment]
Hi @etherum123 - eventually my plan is to support that, but first I want to design a system that allows xrpl4j to more easily support alternative networks. However, I don't have an ETA just yet for either of those.

In the meantime, we do have some work started on hooks (though kinda dormant, so it might be out of date depending on whether hooks have changed at all). Take a look here: https://github.com/XRPLF/xrpl4j/tree/hooks-dev-preview

**Comment by etherum123** [comment]
Thanks David.
