### ISSUE TITLE
Check library against ripple-lib & ripple-binary-codec bugs

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#82]
As this library was ported from ripple JS libraries, we should check this library against the following two bugs:

* [x] Make a unit test to cover this condition: https://github.com/ripple/ripple-lib/issues/1347
* [x] Make a unit test to cover this condition: https://github.com/ripple/ripple-binary-codec/issues/117

**Comment by intelliot** [comment]
and a couple more recent bugs to check on:

- [ ] https://github.com/XRPLF/xrpl.js/pull/1830
- [ ] https://github.com/XRPLF/xrpl.js/pull/1857
